### ISSUE TITLE
random from a json 

### ISSUE THREAD

**Issue by piskello** [alsolovyev/Nunjucks#26]
Hi,
I would get a random item from a .json file: I followed the online docs, so 
{{ [1,2,3,4,5,6,7,8,9] | random }}
but I get always the number 1.
Where I'm getting wrong?

**Comment by alsolovyev** [comment]
Hi, 

this package doesn't change the built-in functions of the nunjucks and is only needed to highlight the synaxis and additional functionality of the editor. Therefore, the problem is in the code itself or the nunjucks. Could you provide a code snippet with your problem?

This code works fine:
```json
{
  "name": "nunjucks-bug",
  "private": true,
  "scripts": {
    "dev": "parcel ./index.njk --port 8080"
  },
  "devDependencies": {
    "parcel": "^2.0.1",
    "babel-types": "^6.26.0",
    "nunjucks": "^3.2.3",
    "parcel-bundler": "^1.12.5",
    "parcel-plugin-data-src": "^1.0.1",
    "parcel-plugin-nunjucks": "^2.2.2",
    "parcel-plugin-svg-sprite": "^1.4.1",
    "sass": "^1.45.1"
  }
}
```

```nunjucks
<!DOCTYPE html>
<html lang='en'>
<head>
  <meta charset='UTF-8'>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>
  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
  <title>Nunjucks</title>
</head>
<body>
  <h1>{{ [1,2,3,4,5,6,7,8,9] | random }}</h1>
</body>
</html>
```

_* to get the random number, you need to rebuild the project each time_

ps my sincerest apologies for the slow response!

**Comment by piskello** [comment]
Dear Aleksey,
No problem for the slow response. In the meantime I discovered e I was using the code correctly. I made a conceptual mistake: the random number is generated only once during the building, and not at any refresh 🤦‍♂️
