### ISSUE TITLE
Errormsg on Sublime Build 4189 from Dec, 20. 2024

### ISSUE THREAD

**Issue by rudwax** [alsolovyev/Nunjucks#27]
The following Message pops up since the new update of Sublime Build 4189 from Dec, 20. 2024

Error loading syntax file "Packages/Nunjucks/Syntaxes/Nunjucks.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit

![2024-12-30_17-48-03](https://github.com/user-attachments/assets/94df68a8-4306-40cd-aede-b710798f4f73)

**Comment by alsolovyev** [comment]
@rudwax, thank you for notifying me about the error in the new version of Sublime Text. Unfortunately, I am not currently using this editor, which is why I wasn't able to notice it promptly. I see that the issue is affecting many user: [#6555](https://github.com/sublimehq/sublime_text/issues/6555), [#6572](https://github.com/sublimehq/sublime_text/issues/6572), etc

I've [released](https://github.com/alsolovyev/Nunjucks/releases/tag/v2.0.3) an update that fixes this issue. Please update the package
